import { FitCssColorVariables } from '../../common/css-variables.js';

export const cssVariables: FitCssColorVariables = {
  '--highlight-color': '#d2550b',
  '--toolbar-background-color': '#383838',
  '--toolbar-background-hover-color': 'rgba(255, 255, 255, 0.2)',
  '--toolbar-color': '#a7a7a7',
  '--toolbar-border-color': '#5d5d5d',
  '--toolbar-box-shadow-color': 'rgba(0, 0, 0, 0.4)',
  '--scrollbar-background-color': '#383838',
  '--scrollbar-color': '#5d5d5d',
  '--scrollbar-border-color': '#383838',
  '--table-header-background-color': '#383838',
  '--table-header-background-hover-color': 'rgba(255, 255, 255, 0.2)',
  '--table-header-color': '#a7a7a7',
  '--table-header-border-color': '#5d5d5d',
  '--table-body-background-color': '#252525',
  '--table-body-color': '#dddddd',
  '--table-body-border-color': '#4a4a4a',
  '--cell-editor-background-color': '#252525',
  '--cell-editor-color': '#dddddd',
  '--cell-editor-box-shadow-color': 'rgba(210, 85, 11, 1)',
  '--cell-selection-background-color': 'rgba(210, 85, 11, 0.1)',
  '--cell-selection-border-color': '#d2550b',
  '--context-menu-background-color': '#383838',
  '--context-menu-background-hover-color': 'rgba(255, 255, 255, 0.1)',
  '--context-menu-color': '#a7a7a7',
  '--context-menu-border-color': '#5d5d5d',
  '--context-menu-box-shadow-color': 'rgba(0, 0, 0, 0.4)',
  '--statusbar-background-color': '#383838',
  '--statusbar-color': '#a7a7a7',
  '--statusbar-border-color': '#5d5d5d',
};
