export type ContentTitle =
  | 'Introduction'
  | 'Installation'
  | 'Row header'
  | 'Row height'
  | 'Column header'
  | 'Column width'
  | 'Cell value'
  | 'Cell style'
  | 'Cell merge'
  | 'Table DTO'
  | 'Table configuration'
  | 'Update style'
  | 'Paint format'
  | 'Resize rows'
  | 'Insert rows above'
  | 'Insert rows below'
  | 'Remove rows'
  | 'Resize columns'
  | 'Insert columns above'
  | 'Insert columns below'
  | 'Remove columns'
  | 'Clear cells'
  | 'Remove cells'
  | 'Cut cells'
  | 'Copy cells'
  | 'Paste cells'
  | 'Merge cells'
  | 'Merge cells'
  | 'Unmerge cells'
  | 'Undo'
  | 'Redo'
  | 'Operation DTO'
  | 'Operation configuration'
  | 'Language dictionary'
  | 'Image registry'
  | 'Table viewer'
  | 'Table scroller'
  | 'Cell selection'
  | 'Cell editor'
  | 'Theme switcher'
  | 'Settings bar'
  | 'Toolbar'
  | 'Context menu'
  | 'Statusbar'
  | 'View model configuration';
