export type TopicTitle =
  | 'Introduction'
  | 'Playground'
  | 'Architecture'
  | 'Installation'
  | 'Row height'
  | 'Column width'
  | 'Cell value'
  | 'Cell style'
  | 'Cell merge'
  | 'Table DTO'
  | 'Custom table'
  | 'Update style'
  | 'Paint format'
  | 'Resize rows'
  | 'Insert rows above'
  | 'Insert rows below'
  | 'Remove rows'
  | 'Resize columns'
  | 'Insert columns left'
  | 'Insert columns right'
  | 'Remove columns'
  | 'Cell values'
  | 'Clear cells'
  | 'Remove cells'
  | 'Cut / Paste cells'
  | 'Copy / Paste cells'
  | 'Merge cells'
  | 'Merge cells'
  | 'Unmerge cells'
  | 'Operation DTO'
  | 'Custom operation'
  | 'Table interoperability'
  | 'Row header'
  | 'Column header'
  | 'Row heights'
  | 'Column widths'
  | 'Column filters (1/2)'
  | 'Column filters (2/2)'
  | 'Language dictionary'
  | 'Image registry'
  | 'Table scroller'
  | 'Cell selection'
  | 'Cell editor'
  | 'Theme switcher'
  | 'Settings bar'
  | 'Toolbar'
  | 'Context menu'
  | 'Statusbar'
  | 'Custom view model';
